### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by gonzalo-** [ykaw/sag#1]
Hi!

I totally love the idea, I tried it but it is too complicated all the steps of creating and editing the "SAGHOME" and such, there is a missing warning that we need to install gnuplot and also there is no "$SAGHOME/plot/common" but "$SAGHOME/plot/common.gp" ?

I found the article in japanese at the Fuguita website which it would be nice to update here too, maybe to make it more complete with examples?

I can help if you want, let me know :)

**Comment by ykaw** [comment]
Hi

Thanks for your comment.

SAG is a very old script, almost a quarter of a century since I created it, and I haven't maintained it recently.
For starters, I would like to update the original https://fuguita.org/SAG to match the current state of the art.
After that, I would like to revise the README to include the points you have pointed out.
The original SAG repository is a CVS repository that I have on hand, so I plan to update that one and reflect it on GitHub.

**Comment by gonzalo-** [comment]
Nice!

https://fuguita.org/SAG got a 404 Not Found

https://fuguita.org/sag has the graphics I want to create with sag!

But no guide, my idea was to make a Makefile or .sh to deploy sag in a clean and fast way, if you give me a proper up-to-date guide I can do it!

Thanks!


On 31 May 2023 23:39:43 CEST, Yoshihiro KAWAMATA ***@***.***> wrote:
;Hi
;
;Thanks for your comment.
;
;SAG is a very old script, almost a quarter of a century since I created it, and I haven't maintained it recently.
;For starters, I would like to update the original https://fuguita.org/SAG to match the current state of the art.
;After that, I would like to revise the README to include the points you have pointed out.
;The original SAG repository is a CVS repository that I have on hand, so I plan to update that one and reflect it on GitHub.
;

**Comment by ykaw** [comment]
Sorry, corrected URL is https://fuguita.org/?SAG .

First, I would like to modify this document to fit the current situation.

I was also thinking about the deployment mechanism.

**Comment by ykaw** [comment]
READMEs enhanced, and INSTALLs introduced

**Comment by gonzalo-** [comment]
thank you so much!

I will try to install it and maybe try to do an automation for it!

本当にありがとうございました。

**Comment by gonzalo-** [comment]
Hi again :)

I am getting this:

```
set terminal png size 640,480 background rgb "black" fontscale 0.7
             ^
"../plot/common.gp" line 43: unknown or ambiguous terminal type; type just 'set terminal' for a list


set terminal png size 640,480 background rgb "black" fontscale 0.7
             ^
"../plot/common.gp" line 43: unknown or ambiguous terminal type; type just 'set terminal' for a list


set terminal png size 640,480 background rgb "black" fontscale 0.7
             ^
"../plot/common.gp" line 43: unknown or ambiguous terminal type; type just 'set terminal' for a list


set terminal png size 640,480 background rgb "black" fontscale 0.7
             ^
"../plot/common.gp" line 43: unknown or ambiguous terminal type; type just 'set terminal' for a list


set terminal png size 640,480 background rgb "black" fontscale 0.7
             ^
"../plot/common.gp" line 43: unknown or ambiguous terminal type; type just 'set terminal' for a list


set terminal png size 640,480 background rgb "black" fontscale 0.7
             ^
"../plot/common.gp" line 43: unknown or ambiguous terminal type; type just 'set terminal' for a list
```

**Comment by ykaw** [comment]
Did you pkg_add gnuplot-5.2.7p1-no_x11, not gnuplot-5.2.7p1?
gnuplot-5.2.7p1-no_x11 doesn't have capability to generate raster image files.

**Comment by gonzalo-** [comment]
Yes, that was it! Thank you very much!
